FROM jenkins/inbound-agent

USER root

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        git \
        clang-tidy \
        clang-format && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
